# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: unversioned
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import k8sclient
from k8sclient.rest import ApiException
from k8sclient.apis.apps_v1alpha1_api import AppsV1alpha1Api


class TestAppsV1alpha1Api(unittest.TestCase):
    """ AppsV1alpha1Api unit test stubs """

    def setUp(self):
        self.api = k8sclient.apis.apps_v1alpha1_api.AppsV1alpha1Api()

    def tearDown(self):
        pass

    def test_create_apps_v1alpha1_namespaced_stateful_set(self):
        """
        Test case for create_apps_v1alpha1_namespaced_stateful_set

        
        """
        pass

    def test_delete_apps_v1alpha1_collection_namespaced_stateful_set(self):
        """
        Test case for delete_apps_v1alpha1_collection_namespaced_stateful_set

        
        """
        pass

    def test_delete_apps_v1alpha1_namespaced_stateful_set(self):
        """
        Test case for delete_apps_v1alpha1_namespaced_stateful_set

        
        """
        pass

    def test_get_apps_v1alpha1_api_resources(self):
        """
        Test case for get_apps_v1alpha1_api_resources

        
        """
        pass

    def test_list_apps_v1alpha1_namespaced_stateful_set(self):
        """
        Test case for list_apps_v1alpha1_namespaced_stateful_set

        
        """
        pass

    def test_list_apps_v1alpha1_stateful_set_for_all_namespaces(self):
        """
        Test case for list_apps_v1alpha1_stateful_set_for_all_namespaces

        
        """
        pass

    def test_patch_apps_v1alpha1_namespaced_stateful_set(self):
        """
        Test case for patch_apps_v1alpha1_namespaced_stateful_set

        
        """
        pass

    def test_patch_apps_v1alpha1_namespaced_stateful_set_status(self):
        """
        Test case for patch_apps_v1alpha1_namespaced_stateful_set_status

        
        """
        pass

    def test_read_apps_v1alpha1_namespaced_stateful_set(self):
        """
        Test case for read_apps_v1alpha1_namespaced_stateful_set

        
        """
        pass

    def test_read_apps_v1alpha1_namespaced_stateful_set_status(self):
        """
        Test case for read_apps_v1alpha1_namespaced_stateful_set_status

        
        """
        pass

    def test_replace_apps_v1alpha1_namespaced_stateful_set(self):
        """
        Test case for replace_apps_v1alpha1_namespaced_stateful_set

        
        """
        pass

    def test_replace_apps_v1alpha1_namespaced_stateful_set_status(self):
        """
        Test case for replace_apps_v1alpha1_namespaced_stateful_set_status

        
        """
        pass

    def test_watch_apps_v1alpha1_namespaced_stateful_set(self):
        """
        Test case for watch_apps_v1alpha1_namespaced_stateful_set

        
        """
        pass

    def test_watch_apps_v1alpha1_namespaced_stateful_set_list(self):
        """
        Test case for watch_apps_v1alpha1_namespaced_stateful_set_list

        
        """
        pass

    def test_watch_apps_v1alpha1_stateful_set_list_for_all_namespaces(self):
        """
        Test case for watch_apps_v1alpha1_stateful_set_list_for_all_namespaces

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
