# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.25
    Generated by: https://openapi-generator.tech
"""

import unittest

import kubernetes.client
from kubernetes.client.model.v1alpha1_storage_version_condition import V1alpha1StorageVersionCondition
from kubernetes.client import configuration


class TestV1alpha1StorageVersionCondition(unittest.TestCase):
    """V1alpha1StorageVersionCondition unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
