# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.25
    Generated by: https://openapi-generator.tech
"""

import unittest

import kubernetes.client
from kubernetes.client.model.v1beta1_group_subject import V1beta1GroupSubject
from kubernetes.client import configuration


class TestV1beta1GroupSubject(unittest.TestCase):
    """V1beta1GroupSubject unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
