# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.25
    Generated by: https://openapi-generator.tech
"""

import unittest

import kubernetes.client
from kubernetes.client.model.v2beta2_cross_version_object_reference import V2beta2CrossVersionObjectReference
from kubernetes.client import configuration


class TestV2beta2CrossVersionObjectReference(unittest.TestCase):
    """V2beta2CrossVersionObjectReference unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
