# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.25
    Generated by: https://openapi-generator.tech
"""

import unittest

import kubernetes.client
from kubernetes.client.model.v1_api_group_list import V1APIGroupList
from kubernetes.client import configuration


class TestV1APIGroupList(unittest.TestCase):
    """V1APIGroupList unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
