# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: release-1.16
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.networking_v1beta1_http_ingress_rule_value import NetworkingV1beta1HTTPIngressRuleValue  # noqa: E501
from kubernetes.client.rest import ApiException


class TestNetworkingV1beta1HTTPIngressRuleValue(unittest.TestCase):
    """NetworkingV1beta1HTTPIngressRuleValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkingV1beta1HTTPIngressRuleValue(self):
        """Test NetworkingV1beta1HTTPIngressRuleValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.networking_v1beta1_http_ingress_rule_value.NetworkingV1beta1HTTPIngressRuleValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
