# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: release-1.16
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.v1alpha1_endpoint_port import V1alpha1EndpointPort  # noqa: E501
from kubernetes.client.rest import ApiException


class TestV1alpha1EndpointPort(unittest.TestCase):
    """V1alpha1EndpointPort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1EndpointPort(self):
        """Test V1alpha1EndpointPort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.v1alpha1_endpoint_port.V1alpha1EndpointPort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
