# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1_named_rule_with_operations import V1NamedRuleWithOperations

class TestV1NamedRuleWithOperations(unittest.TestCase):
    """V1NamedRuleWithOperations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1NamedRuleWithOperations:
        """Test V1NamedRuleWithOperations
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1NamedRuleWithOperations`
        """
        model = V1NamedRuleWithOperations()
        if include_optional:
            return V1NamedRuleWithOperations(
                api_groups = [
                    ''
                    ],
                api_versions = [
                    ''
                    ],
                operations = [
                    ''
                    ],
                resource_names = [
                    ''
                    ],
                resources = [
                    ''
                    ],
                scope = ''
            )
        else:
            return V1NamedRuleWithOperations(
        )
        """

    def testV1NamedRuleWithOperations(self):
        """Test V1NamedRuleWithOperations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
