# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.flowcontrol_v1_subject import FlowcontrolV1Subject

class TestFlowcontrolV1Subject(unittest.TestCase):
    """FlowcontrolV1Subject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlowcontrolV1Subject:
        """Test FlowcontrolV1Subject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlowcontrolV1Subject`
        """
        model = FlowcontrolV1Subject()
        if include_optional:
            return FlowcontrolV1Subject(
                group = kubernetes.client.models.v1/group_subject.v1.GroupSubject(
                    name = '', ),
                kind = '',
                service_account = kubernetes.client.models.v1/service_account_subject.v1.ServiceAccountSubject(
                    name = '', 
                    namespace = '', ),
                user = kubernetes.client.models.v1/user_subject.v1.UserSubject(
                    name = '', )
            )
        else:
            return FlowcontrolV1Subject(
                kind = '',
        )
        """

    def testFlowcontrolV1Subject(self):
        """Test FlowcontrolV1Subject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
