# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubernetes.client
from kubernetes.client.rest import ApiException
from kubernetes.client.models.v1_volume_attachment_list import V1VolumeAttachmentList


class TestV1VolumeAttachmentList(unittest.TestCase):
    """ V1VolumeAttachmentList unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1VolumeAttachmentList(self):
        """
        Test V1VolumeAttachmentList
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubernetes.client.models.v1_volume_attachment_list.V1VolumeAttachmentList()
        pass


if __name__ == '__main__':
    unittest.main()
