# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1.5.1-660c2a2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubernetes.client
from kubernetes.client.rest import ApiException
from kubernetes.client.models.v1_object_meta import V1ObjectMeta


class TestV1ObjectMeta(unittest.TestCase):
    """ V1ObjectMeta unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ObjectMeta(self):
        """
        Test V1ObjectMeta
        """
        model = kubernetes.client.models.v1_object_meta.V1ObjectMeta()


if __name__ == '__main__':
    unittest.main()
