# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.api.flowcontrol_apiserver_v1beta3_api import FlowcontrolApiserverV1beta3Api


class TestFlowcontrolApiserverV1beta3Api(unittest.TestCase):
    """FlowcontrolApiserverV1beta3Api unit test stubs"""

    def setUp(self) -> None:
        self.api = FlowcontrolApiserverV1beta3Api()

    def tearDown(self) -> None:
        pass

    def test_create_flow_schema(self) -> None:
        """Test case for create_flow_schema

        """
        pass

    def test_create_priority_level_configuration(self) -> None:
        """Test case for create_priority_level_configuration

        """
        pass

    def test_delete_collection_flow_schema(self) -> None:
        """Test case for delete_collection_flow_schema

        """
        pass

    def test_delete_collection_priority_level_configuration(self) -> None:
        """Test case for delete_collection_priority_level_configuration

        """
        pass

    def test_delete_flow_schema(self) -> None:
        """Test case for delete_flow_schema

        """
        pass

    def test_delete_priority_level_configuration(self) -> None:
        """Test case for delete_priority_level_configuration

        """
        pass

    def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass

    def test_list_flow_schema(self) -> None:
        """Test case for list_flow_schema

        """
        pass

    def test_list_priority_level_configuration(self) -> None:
        """Test case for list_priority_level_configuration

        """
        pass

    def test_patch_flow_schema(self) -> None:
        """Test case for patch_flow_schema

        """
        pass

    def test_patch_flow_schema_status(self) -> None:
        """Test case for patch_flow_schema_status

        """
        pass

    def test_patch_priority_level_configuration(self) -> None:
        """Test case for patch_priority_level_configuration

        """
        pass

    def test_patch_priority_level_configuration_status(self) -> None:
        """Test case for patch_priority_level_configuration_status

        """
        pass

    def test_read_flow_schema(self) -> None:
        """Test case for read_flow_schema

        """
        pass

    def test_read_flow_schema_status(self) -> None:
        """Test case for read_flow_schema_status

        """
        pass

    def test_read_priority_level_configuration(self) -> None:
        """Test case for read_priority_level_configuration

        """
        pass

    def test_read_priority_level_configuration_status(self) -> None:
        """Test case for read_priority_level_configuration_status

        """
        pass

    def test_replace_flow_schema(self) -> None:
        """Test case for replace_flow_schema

        """
        pass

    def test_replace_flow_schema_status(self) -> None:
        """Test case for replace_flow_schema_status

        """
        pass

    def test_replace_priority_level_configuration(self) -> None:
        """Test case for replace_priority_level_configuration

        """
        pass

    def test_replace_priority_level_configuration_status(self) -> None:
        """Test case for replace_priority_level_configuration_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
