# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1.15.6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.networking_v1beta1_ingress_spec import NetworkingV1beta1IngressSpec  # noqa: E501
from kubernetes.client.rest import ApiException


class TestNetworkingV1beta1IngressSpec(unittest.TestCase):
    """NetworkingV1beta1IngressSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkingV1beta1IngressSpec(self):
        """Test NetworkingV1beta1IngressSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.networking_v1beta1_ingress_spec.NetworkingV1beta1IngressSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
