# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1_azure_file_persistent_volume_source import V1AzureFilePersistentVolumeSource

class TestV1AzureFilePersistentVolumeSource(unittest.TestCase):
    """V1AzureFilePersistentVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AzureFilePersistentVolumeSource:
        """Test V1AzureFilePersistentVolumeSource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AzureFilePersistentVolumeSource`
        """
        model = V1AzureFilePersistentVolumeSource()
        if include_optional:
            return V1AzureFilePersistentVolumeSource(
                read_only = True,
                secret_name = '',
                secret_namespace = '',
                share_name = ''
            )
        else:
            return V1AzureFilePersistentVolumeSource(
                secret_name = '',
                share_name = '',
        )
        """

    def testV1AzureFilePersistentVolumeSource(self):
        """Test V1AzureFilePersistentVolumeSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
