# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1.12.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubernetes.client
from kubernetes.client.rest import ApiException
from kubernetes.client.models.v1_service_reference import V1ServiceReference


class TestV1ServiceReference(unittest.TestCase):
    """ V1ServiceReference unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ServiceReference(self):
        """
        Test V1ServiceReference
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubernetes.client.models.v1_service_reference.V1ServiceReference()
        pass


if __name__ == '__main__':
    unittest.main()
