# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1.15.6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.extensions_v1beta1_deployment_strategy import ExtensionsV1beta1DeploymentStrategy  # noqa: E501
from kubernetes.client.rest import ApiException


class TestExtensionsV1beta1DeploymentStrategy(unittest.TestCase):
    """ExtensionsV1beta1DeploymentStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtensionsV1beta1DeploymentStrategy(self):
        """Test ExtensionsV1beta1DeploymentStrategy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.extensions_v1beta1_deployment_strategy.ExtensionsV1beta1DeploymentStrategy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
