# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: release-1.16
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.v1_node_selector_requirement import V1NodeSelectorRequirement  # noqa: E501
from kubernetes.client.rest import ApiException


class TestV1NodeSelectorRequirement(unittest.TestCase):
    """V1NodeSelectorRequirement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1NodeSelectorRequirement(self):
        """Test V1NodeSelectorRequirement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.v1_node_selector_requirement.V1NodeSelectorRequirement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
