# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.16
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.v2beta1_horizontal_pod_autoscaler_list import V2beta1HorizontalPodAutoscalerList  # noqa: E501
from kubernetes.client.rest import ApiException

class TestV2beta1HorizontalPodAutoscalerList(unittest.TestCase):
    """V2beta1HorizontalPodAutoscalerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V2beta1HorizontalPodAutoscalerList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.v2beta1_horizontal_pod_autoscaler_list.V2beta1HorizontalPodAutoscalerList()  # noqa: E501
        if include_optional :
            return V2beta1HorizontalPodAutoscalerList(
                api_version = '0', 
                items = [
                    kubernetes.client.models.v2beta1/horizontal_pod_autoscaler.v2beta1.HorizontalPodAutoscaler(
                        api_version = '0', 
                        kind = '0', 
                        metadata = kubernetes.client.models.v1/object_meta.v1.ObjectMeta(
                            annotations = {
                                'key' : '0'
                                }, 
                            cluster_name = '0', 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_grace_period_seconds = 56, 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                '0'
                                ], 
                            generate_name = '0', 
                            generation = 56, 
                            labels = {
                                'key' : '0'
                                }, 
                            managed_fields = [
                                kubernetes.client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                                    api_version = '0', 
                                    fields_type = '0', 
                                    fields_v1 = kubernetes.client.models.fields_v1.fieldsV1(), 
                                    manager = '0', 
                                    operation = '0', 
                                    time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            name = '0', 
                            namespace = '0', 
                            owner_references = [
                                kubernetes.client.models.v1/owner_reference.v1.OwnerReference(
                                    api_version = '0', 
                                    block_owner_deletion = True, 
                                    controller = True, 
                                    kind = '0', 
                                    name = '0', 
                                    uid = '0', )
                                ], 
                            resource_version = '0', 
                            self_link = '0', 
                            uid = '0', ), 
                        spec = kubernetes.client.models.v2beta1/horizontal_pod_autoscaler_spec.v2beta1.HorizontalPodAutoscalerSpec(
                            max_replicas = 56, 
                            metrics = [
                                kubernetes.client.models.v2beta1/metric_spec.v2beta1.MetricSpec(
                                    external = kubernetes.client.models.v2beta1/external_metric_source.v2beta1.ExternalMetricSource(
                                        metric_name = '0', 
                                        metric_selector = kubernetes.client.models.v1/label_selector.v1.LabelSelector(
                                            match_expressions = [
                                                kubernetes.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                                    key = '0', 
                                                    operator = '0', 
                                                    values = [
                                                        '0'
                                                        ], )
                                                ], 
                                            match_labels = {
                                                'key' : '0'
                                                }, ), 
                                        target_average_value = '0', 
                                        target_value = '0', ), 
                                    object = kubernetes.client.models.v2beta1/object_metric_source.v2beta1.ObjectMetricSource(
                                        average_value = '0', 
                                        metric_name = '0', 
                                        selector = kubernetes.client.models.v1/label_selector.v1.LabelSelector(), 
                                        target = kubernetes.client.models.v2beta1/cross_version_object_reference.v2beta1.CrossVersionObjectReference(
                                            api_version = '0', 
                                            kind = '0', 
                                            name = '0', ), 
                                        target_value = '0', ), 
                                    pods = kubernetes.client.models.v2beta1/pods_metric_source.v2beta1.PodsMetricSource(
                                        metric_name = '0', 
                                        target_average_value = '0', ), 
                                    resource = kubernetes.client.models.v2beta1/resource_metric_source.v2beta1.ResourceMetricSource(
                                        name = '0', 
                                        target_average_utilization = 56, 
                                        target_average_value = '0', ), 
                                    type = '0', )
                                ], 
                            min_replicas = 56, 
                            scale_target_ref = kubernetes.client.models.v2beta1/cross_version_object_reference.v2beta1.CrossVersionObjectReference(
                                api_version = '0', 
                                kind = '0', 
                                name = '0', ), ), 
                        status = kubernetes.client.models.v2beta1/horizontal_pod_autoscaler_status.v2beta1.HorizontalPodAutoscalerStatus(
                            conditions = [
                                kubernetes.client.models.v2beta1/horizontal_pod_autoscaler_condition.v2beta1.HorizontalPodAutoscalerCondition(
                                    last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    message = '0', 
                                    reason = '0', 
                                    status = '0', 
                                    type = '0', )
                                ], 
                            current_metrics = [
                                kubernetes.client.models.v2beta1/metric_status.v2beta1.MetricStatus(
                                    type = '0', )
                                ], 
                            current_replicas = 56, 
                            desired_replicas = 56, 
                            last_scale_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            observed_generation = 56, ), )
                    ], 
                kind = '0', 
                metadata = kubernetes.client.models.v1/list_meta.v1.ListMeta(
                    continue = '0', 
                    remaining_item_count = 56, 
                    resource_version = '0', 
                    self_link = '0', )
            )
        else :
            return V2beta1HorizontalPodAutoscalerList(
                items = [
                    kubernetes.client.models.v2beta1/horizontal_pod_autoscaler.v2beta1.HorizontalPodAutoscaler(
                        api_version = '0', 
                        kind = '0', 
                        metadata = kubernetes.client.models.v1/object_meta.v1.ObjectMeta(
                            annotations = {
                                'key' : '0'
                                }, 
                            cluster_name = '0', 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_grace_period_seconds = 56, 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                '0'
                                ], 
                            generate_name = '0', 
                            generation = 56, 
                            labels = {
                                'key' : '0'
                                }, 
                            managed_fields = [
                                kubernetes.client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                                    api_version = '0', 
                                    fields_type = '0', 
                                    fields_v1 = kubernetes.client.models.fields_v1.fieldsV1(), 
                                    manager = '0', 
                                    operation = '0', 
                                    time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            name = '0', 
                            namespace = '0', 
                            owner_references = [
                                kubernetes.client.models.v1/owner_reference.v1.OwnerReference(
                                    api_version = '0', 
                                    block_owner_deletion = True, 
                                    controller = True, 
                                    kind = '0', 
                                    name = '0', 
                                    uid = '0', )
                                ], 
                            resource_version = '0', 
                            self_link = '0', 
                            uid = '0', ), 
                        spec = kubernetes.client.models.v2beta1/horizontal_pod_autoscaler_spec.v2beta1.HorizontalPodAutoscalerSpec(
                            max_replicas = 56, 
                            metrics = [
                                kubernetes.client.models.v2beta1/metric_spec.v2beta1.MetricSpec(
                                    external = kubernetes.client.models.v2beta1/external_metric_source.v2beta1.ExternalMetricSource(
                                        metric_name = '0', 
                                        metric_selector = kubernetes.client.models.v1/label_selector.v1.LabelSelector(
                                            match_expressions = [
                                                kubernetes.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                                    key = '0', 
                                                    operator = '0', 
                                                    values = [
                                                        '0'
                                                        ], )
                                                ], 
                                            match_labels = {
                                                'key' : '0'
                                                }, ), 
                                        target_average_value = '0', 
                                        target_value = '0', ), 
                                    object = kubernetes.client.models.v2beta1/object_metric_source.v2beta1.ObjectMetricSource(
                                        average_value = '0', 
                                        metric_name = '0', 
                                        selector = kubernetes.client.models.v1/label_selector.v1.LabelSelector(), 
                                        target = kubernetes.client.models.v2beta1/cross_version_object_reference.v2beta1.CrossVersionObjectReference(
                                            api_version = '0', 
                                            kind = '0', 
                                            name = '0', ), 
                                        target_value = '0', ), 
                                    pods = kubernetes.client.models.v2beta1/pods_metric_source.v2beta1.PodsMetricSource(
                                        metric_name = '0', 
                                        target_average_value = '0', ), 
                                    resource = kubernetes.client.models.v2beta1/resource_metric_source.v2beta1.ResourceMetricSource(
                                        name = '0', 
                                        target_average_utilization = 56, 
                                        target_average_value = '0', ), 
                                    type = '0', )
                                ], 
                            min_replicas = 56, 
                            scale_target_ref = kubernetes.client.models.v2beta1/cross_version_object_reference.v2beta1.CrossVersionObjectReference(
                                api_version = '0', 
                                kind = '0', 
                                name = '0', ), ), 
                        status = kubernetes.client.models.v2beta1/horizontal_pod_autoscaler_status.v2beta1.HorizontalPodAutoscalerStatus(
                            conditions = [
                                kubernetes.client.models.v2beta1/horizontal_pod_autoscaler_condition.v2beta1.HorizontalPodAutoscalerCondition(
                                    last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    message = '0', 
                                    reason = '0', 
                                    status = '0', 
                                    type = '0', )
                                ], 
                            current_metrics = [
                                kubernetes.client.models.v2beta1/metric_status.v2beta1.MetricStatus(
                                    type = '0', )
                                ], 
                            current_replicas = 56, 
                            desired_replicas = 56, 
                            last_scale_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            observed_generation = 56, ), )
                    ],
        )

    def testV2beta1HorizontalPodAutoscalerList(self):
        """Test V2beta1HorizontalPodAutoscalerList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
