# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.17
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.v1_downward_api_volume_file import V1DownwardAPIVolumeFile  # noqa: E501
from kubernetes.client.rest import ApiException

class TestV1DownwardAPIVolumeFile(unittest.TestCase):
    """V1DownwardAPIVolumeFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1DownwardAPIVolumeFile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.v1_downward_api_volume_file.V1DownwardAPIVolumeFile()  # noqa: E501
        if include_optional :
            return V1DownwardAPIVolumeFile(
                field_ref = kubernetes.client.models.v1/object_field_selector.v1.ObjectFieldSelector(
                    api_version = '0', 
                    field_path = '0', ), 
                mode = 56, 
                path = '0', 
                resource_field_ref = kubernetes.client.models.v1/resource_field_selector.v1.ResourceFieldSelector(
                    container_name = '0', 
                    divisor = '0', 
                    resource = '0', )
            )
        else :
            return V1DownwardAPIVolumeFile(
                path = '0',
        )

    def testV1DownwardAPIVolumeFile(self):
        """Test V1DownwardAPIVolumeFile"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
