# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: release-1.15
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import client
from client.models.v1_persistent_volume_claim import V1PersistentVolumeClaim  # noqa: E501
from client.rest import ApiException


class TestV1PersistentVolumeClaim(unittest.TestCase):
    """V1PersistentVolumeClaim unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1PersistentVolumeClaim(self):
        """Test V1PersistentVolumeClaim"""
        # FIXME: construct object with mandatory attributes with example values
        # model = client.models.v1_persistent_volume_claim.V1PersistentVolumeClaim()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
