# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubernetes.client
from kubernetes.client.rest import ApiException
from kubernetes.client.models.v1beta1_volume_attachment_spec import V1beta1VolumeAttachmentSpec


class TestV1beta1VolumeAttachmentSpec(unittest.TestCase):
    """ V1beta1VolumeAttachmentSpec unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1VolumeAttachmentSpec(self):
        """
        Test V1beta1VolumeAttachmentSpec
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubernetes.client.models.v1beta1_volume_attachment_spec.V1beta1VolumeAttachmentSpec()
        pass


if __name__ == '__main__':
    unittest.main()
