# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: release-1.15
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import client
from client.models.v1_self_subject_rules_review import V1SelfSubjectRulesReview  # noqa: E501
from client.rest import ApiException


class TestV1SelfSubjectRulesReview(unittest.TestCase):
    """V1SelfSubjectRulesReview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1SelfSubjectRulesReview(self):
        """Test V1SelfSubjectRulesReview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = client.models.v1_self_subject_rules_review.V1SelfSubjectRulesReview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
