# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: release-1.16
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.v1beta2_scale_spec import V1beta2ScaleSpec  # noqa: E501
from kubernetes.client.rest import ApiException


class TestV1beta2ScaleSpec(unittest.TestCase):
    """V1beta2ScaleSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta2ScaleSpec(self):
        """Test V1beta2ScaleSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.v1beta2_scale_spec.V1beta2ScaleSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
