# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1.5.1-660c2a2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubernetes.client
from kubernetes.client.rest import ApiException
from kubernetes.client.models.v1alpha1_certificate_signing_request_status import V1alpha1CertificateSigningRequestStatus


class TestV1alpha1CertificateSigningRequestStatus(unittest.TestCase):
    """ V1alpha1CertificateSigningRequestStatus unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1CertificateSigningRequestStatus(self):
        """
        Test V1alpha1CertificateSigningRequestStatus
        """
        model = kubernetes.client.models.v1alpha1_certificate_signing_request_status.V1alpha1CertificateSigningRequestStatus()


if __name__ == '__main__':
    unittest.main()
