# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1.12.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubernetes.client
from kubernetes.client.rest import ApiException
from kubernetes.client.models.extensions_v1beta1_pod_security_policy_list import ExtensionsV1beta1PodSecurityPolicyList


class TestExtensionsV1beta1PodSecurityPolicyList(unittest.TestCase):
    """ ExtensionsV1beta1PodSecurityPolicyList unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtensionsV1beta1PodSecurityPolicyList(self):
        """
        Test ExtensionsV1beta1PodSecurityPolicyList
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubernetes.client.models.extensions_v1beta1_pod_security_policy_list.ExtensionsV1beta1PodSecurityPolicyList()
        pass


if __name__ == '__main__':
    unittest.main()
