# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1.13.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.v1beta1_http_ingress_path import V1beta1HTTPIngressPath  # noqa: E501
from kubernetes.client.rest import ApiException


class TestV1beta1HTTPIngressPath(unittest.TestCase):
    """V1beta1HTTPIngressPath unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1HTTPIngressPath(self):
        """Test V1beta1HTTPIngressPath"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.v1beta1_http_ingress_path.V1beta1HTTPIngressPath()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
