# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v1_success_policy import V1SuccessPolicy

class TestV1SuccessPolicy(unittest.TestCase):
    """V1SuccessPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SuccessPolicy:
        """Test V1SuccessPolicy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SuccessPolicy`
        """
        model = V1SuccessPolicy()
        if include_optional:
            return V1SuccessPolicy(
                rules = [
                    kubernetes.client.models.v1/success_policy_rule.v1.SuccessPolicyRule(
                        succeeded_count = 56, 
                        succeeded_indexes = '', )
                    ]
            )
        else:
            return V1SuccessPolicy(
                rules = [
                    kubernetes.client.models.v1/success_policy_rule.v1.SuccessPolicyRule(
                        succeeded_count = 56, 
                        succeeded_indexes = '', )
                    ],
        )
        """

    def testV1SuccessPolicy(self):
        """Test V1SuccessPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
