# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kubernetes.client.models.v2_horizontal_pod_autoscaler_behavior import V2HorizontalPodAutoscalerBehavior

class TestV2HorizontalPodAutoscalerBehavior(unittest.TestCase):
    """V2HorizontalPodAutoscalerBehavior unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2HorizontalPodAutoscalerBehavior:
        """Test V2HorizontalPodAutoscalerBehavior
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2HorizontalPodAutoscalerBehavior`
        """
        model = V2HorizontalPodAutoscalerBehavior()
        if include_optional:
            return V2HorizontalPodAutoscalerBehavior(
                scale_down = kubernetes.client.models.v2/hpa_scaling_rules.v2.HPAScalingRules(
                    policies = [
                        kubernetes.client.models.v2/hpa_scaling_policy.v2.HPAScalingPolicy(
                            period_seconds = 56, 
                            type = '', 
                            value = 56, )
                        ], 
                    select_policy = '', 
                    stabilization_window_seconds = 56, ),
                scale_up = kubernetes.client.models.v2/hpa_scaling_rules.v2.HPAScalingRules(
                    policies = [
                        kubernetes.client.models.v2/hpa_scaling_policy.v2.HPAScalingPolicy(
                            period_seconds = 56, 
                            type = '', 
                            value = 56, )
                        ], 
                    select_policy = '', 
                    stabilization_window_seconds = 56, )
            )
        else:
            return V2HorizontalPodAutoscalerBehavior(
        )
        """

    def testV2HorizontalPodAutoscalerBehavior(self):
        """Test V2HorizontalPodAutoscalerBehavior"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
