# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.36
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from kubernetes.client.models.v1_flow_distinguisher_method import V1FlowDistinguisherMethod
from kubernetes.client.models.v1_policy_rules_with_subjects import V1PolicyRulesWithSubjects
from kubernetes.client.models.v1_priority_level_configuration_reference import V1PriorityLevelConfigurationReference
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class V1FlowSchemaSpec(BaseModel):
    """
    FlowSchemaSpec describes how the FlowSchema's specification looks like.

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    distinguisher_method: Optional[V1FlowDistinguisherMethod] = Field(default=None, validation_alias=AliasChoices("distinguisherMethod", "distinguisher_method"), serialization_alias="distinguisherMethod")
    matching_precedence: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("matchingPrecedence", "matching_precedence"), serialization_alias="matchingPrecedence", description="`matchingPrecedence` is used to choose among the FlowSchemas that match a given request. The chosen FlowSchema is among those with the numerically lowest (which we take to be logically highest) MatchingPrecedence.  Each MatchingPrecedence value must be ranged in [1,10000]. Note that if the precedence is not specified, it will be set to 1000 as default.")
    priority_level_configuration: V1PriorityLevelConfigurationReference = Field(validation_alias=AliasChoices("priorityLevelConfiguration", "priority_level_configuration"), serialization_alias="priorityLevelConfiguration")
    rules: Optional[List[V1PolicyRulesWithSubjects]] = Field(default=None, description="`rules` describes which requests will match this flow schema. This FlowSchema matches a request if and only if at least one member of rules matches the request. if it is an empty slice, there will be no requests matching the FlowSchema.")
    openapi_types: ClassVar[Dict[str, str]] = {
        "distinguisher_method": "V1FlowDistinguisherMethod",
        "matching_precedence": "int",
        "priority_level_configuration": "V1PriorityLevelConfigurationReference",
        "rules": "List[V1PolicyRulesWithSubjects]"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "distinguisher_method": "distinguisherMethod",
        "matching_precedence": "matchingPrecedence",
        "priority_level_configuration": "priorityLevelConfiguration",
        "rules": "rules"
    }
    __properties: ClassVar[List[str]] = ["distinguisherMethod", "matchingPrecedence", "priorityLevelConfiguration", "rules"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "distinguisherMethod" not in obj and "distinguisher_method" in obj:
            obj["distinguisherMethod"] = obj["distinguisher_method"]
        obj.pop("distinguisher_method", None)
        if "matchingPrecedence" not in obj and "matching_precedence" in obj:
            obj["matchingPrecedence"] = obj["matching_precedence"]
        obj.pop("matching_precedence", None)
        if "priorityLevelConfiguration" not in obj and "priority_level_configuration" in obj:
            obj["priorityLevelConfiguration"] = obj["priority_level_configuration"]
        obj.pop("priority_level_configuration", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1FlowSchemaSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1FlowSchemaSpec):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1FlowSchemaSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("distinguisherMethod" if serialize else "distinguisher_method"): _to_legacy_value(getattr(self, "distinguisher_method", None), serialize),
            ("matchingPrecedence" if serialize else "matching_precedence"): _to_legacy_value(getattr(self, "matching_precedence", None), serialize),
            ("priorityLevelConfiguration" if serialize else "priority_level_configuration"): _to_legacy_value(getattr(self, "priority_level_configuration", None), serialize),
            ("rules" if serialize else "rules"): _to_legacy_value(getattr(self, "rules", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of distinguisher_method
        if self.distinguisher_method:
            _dict['distinguisherMethod'] = _to_openapi_value(self.distinguisher_method)
        # override the default output from pydantic by calling `to_dict()` of priority_level_configuration
        if self.priority_level_configuration:
            _dict['priorityLevelConfiguration'] = _to_openapi_value(self.priority_level_configuration)
        # override the default output from pydantic by calling `to_dict()` of each item in rules (list)
        _items = []
        if self.rules:
            for _item_rules in self.rules:
                if _item_rules:
                    _items.append(_to_openapi_value(_item_rules))
            _dict['rules'] = _items
        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1FlowSchemaSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "distinguisherMethod": V1FlowDistinguisherMethod.from_dict(obj["distinguisherMethod"]) if obj.get("distinguisherMethod") is not None else None,
            "matchingPrecedence": obj.get("matchingPrecedence"),
            "priorityLevelConfiguration": V1PriorityLevelConfigurationReference.from_dict(obj["priorityLevelConfiguration"]) if obj.get("priorityLevelConfiguration") is not None else None,
            "rules": [V1PolicyRulesWithSubjects.from_dict(_item) for _item in obj["rules"]] if obj.get("rules") is not None else None
        })
        return _obj
