# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from kubernetes.client.models.v1alpha2_resource_request import V1alpha2ResourceRequest
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class V1alpha2DriverRequests(BaseModel):
    """
    DriverRequests describes all resources that are needed from one particular driver.
    """ # noqa: E501
    driver_name: Optional[StrictStr] = Field(default=None, description="DriverName is the name used by the DRA driver kubelet plugin.", alias="driverName")
    requests: Optional[List[V1alpha2ResourceRequest]] = Field(default=None, description="Requests describes all resources that are needed from the driver.")
    vendor_parameters: Optional[Dict[str, Any]] = Field(default=None, description="VendorParameters are arbitrary setup parameters for all requests of the claim. They are ignored while allocating the claim.", alias="vendorParameters")
    __properties: ClassVar[List[str]] = ["driverName", "requests", "vendorParameters"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1alpha2DriverRequests from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in requests (list)
        _items = []
        if self.requests:
            for _item in self.requests:
                if _item:
                    _items.append(_item.to_dict())
            _dict['requests'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of V1alpha2DriverRequests from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "driverName": obj.get("driverName"),
            "requests": [V1alpha2ResourceRequest.from_dict(_item) for _item in obj.get("requests")] if obj.get("requests") is not None else None,
            "vendorParameters": obj.get("vendorParameters")
        })
        return _obj


