apiVersion: v1
kind: Service
metadata:
  name: mock-2
  labels:
    app: mock-2
spec:
  ports:
  - port: 99
    protocol: TCP
    targetPort: 9949
  selector:
    app: mock-2
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mock-2
spec:
  replicas: 1
  selector:
    app: mock-2
  template:
    metadata:
      labels:
        app: mock-2
    spec:
      containers:
      - name: mock-container
        image: k8s.gcr.io/pause:2.0
        ports:
        - containerPort: 9949
          protocol: TCP