# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.25
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from client import schemas  # noqa: F401


class V1NodeDaemonEndpoints(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    NodeDaemonEndpoints lists ports opened by daemons running on the Node.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def kubeletEndpoint() -> typing.Type['V1DaemonEndpoint']:
                return V1DaemonEndpoint
            __annotations__ = {
                "kubeletEndpoint": kubeletEndpoint,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubeletEndpoint"]) -> 'V1DaemonEndpoint': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["kubeletEndpoint", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubeletEndpoint"]) -> typing.Union['V1DaemonEndpoint', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["kubeletEndpoint", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        kubeletEndpoint: typing.Union['V1DaemonEndpoint', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'V1NodeDaemonEndpoints':
        return super().__new__(
            cls,
            *args,
            kubeletEndpoint=kubeletEndpoint,
            _configuration=_configuration,
            **kwargs,
        )

from client.model.v1_daemon_endpoint import V1DaemonEndpoint
