[tox]
skipsdist = True
envlist =
   py3{8,9}
   py31{0,1,2,3,4,5}
   py3{8,9}-functional
   py31{0,1,2,3,4,5}-functional

[testenv]
passenv =
   TOXENV
   CI
   TRAVIS
   TRAVIS_*
deps =
   pytest
commands =
   python -V
   pytest
   ./run_tox.sh pytest

