# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from kubernetes.client.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    WELL_KNOWN = "WellKnown"
    ADMISSIONREGISTRATION = "admissionregistration"
    ADMISSIONREGISTRATION_V1 = "admissionregistration_v1"
    APIEXTENSIONS = "apiextensions"
    APIEXTENSIONS_V1 = "apiextensions_v1"
    APIREGISTRATION = "apiregistration"
    APIREGISTRATION_V1 = "apiregistration_v1"
    APIS = "apis"
    APPS = "apps"
    APPS_V1 = "apps_v1"
    AUTHENTICATION = "authentication"
    AUTHENTICATION_V1 = "authentication_v1"
    AUTHORIZATION = "authorization"
    AUTHORIZATION_V1 = "authorization_v1"
    AUTOSCALING = "autoscaling"
    AUTOSCALING_V1 = "autoscaling_v1"
    AUTOSCALING_V2 = "autoscaling_v2"
    AUTOSCALING_V2BETA2 = "autoscaling_v2beta2"
    BATCH = "batch"
    BATCH_V1 = "batch_v1"
    CERTIFICATES = "certificates"
    CERTIFICATES_V1 = "certificates_v1"
    COORDINATION = "coordination"
    COORDINATION_V1 = "coordination_v1"
    CORE = "core"
    CORE_V1 = "core_v1"
    CUSTOM_OBJECTS = "custom_objects"
    DISCOVERY = "discovery"
    DISCOVERY_V1 = "discovery_v1"
    EVENTS = "events"
    EVENTS_V1 = "events_v1"
    FLOWCONTROL_APISERVER = "flowcontrolApiserver"
    FLOWCONTROL_APISERVER_V1BETA1 = "flowcontrolApiserver_v1beta1"
    FLOWCONTROL_APISERVER_V1BETA2 = "flowcontrolApiserver_v1beta2"
    INTERNAL_APISERVER = "internalApiserver"
    INTERNAL_APISERVER_V1ALPHA1 = "internalApiserver_v1alpha1"
    LOGS = "logs"
    NETWORKING = "networking"
    NETWORKING_V1 = "networking_v1"
    NETWORKING_V1ALPHA1 = "networking_v1alpha1"
    NODE = "node"
    NODE_V1 = "node_v1"
    OPENID = "openid"
    POLICY = "policy"
    POLICY_V1 = "policy_v1"
    RBAC_AUTHORIZATION = "rbacAuthorization"
    RBAC_AUTHORIZATION_V1 = "rbacAuthorization_v1"
    SCHEDULING = "scheduling"
    SCHEDULING_V1 = "scheduling_v1"
    STORAGE = "storage"
    STORAGE_V1 = "storage_v1"
    STORAGE_V1BETA1 = "storage_v1beta1"
    VERSION = "version"
