# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: release-1.25
    Generated by: https://openapi-generator.tech
"""

from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests.post import CreateCertificateSigningRequest
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests_name.delete import DeleteCertificateSigningRequest
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests.delete import DeleteCollectionCertificateSigningRequest
from kubernetes.client.paths.apis_certificates_k8s_io_v1_.get import GetApiResources
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests.get import ListCertificateSigningRequest
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests_name.patch import PatchCertificateSigningRequest
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests_name_approval.patch import PatchCertificateSigningRequestApproval
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests_name_status.patch import PatchCertificateSigningRequestStatus
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests_name.get import ReadCertificateSigningRequest
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests_name_approval.get import ReadCertificateSigningRequestApproval
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests_name_status.get import ReadCertificateSigningRequestStatus
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests_name.put import ReplaceCertificateSigningRequest
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests_name_approval.put import ReplaceCertificateSigningRequestApproval
from kubernetes.client.paths.apis_certificates_k8s_io_v1_certificatesigningrequests_name_status.put import ReplaceCertificateSigningRequestStatus


class CertificatesV1Api(
    CreateCertificateSigningRequest,
    DeleteCertificateSigningRequest,
    DeleteCollectionCertificateSigningRequest,
    GetApiResources,
    ListCertificateSigningRequest,
    PatchCertificateSigningRequest,
    PatchCertificateSigningRequestApproval,
    PatchCertificateSigningRequestStatus,
    ReadCertificateSigningRequest,
    ReadCertificateSigningRequestApproval,
    ReadCertificateSigningRequestStatus,
    ReplaceCertificateSigningRequest,
    ReplaceCertificateSigningRequestApproval,
    ReplaceCertificateSigningRequestStatus,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
